In [1]:
import gym
import numpy as np
from gym import envs

In [2]:
#View all the envs to choose from
sorted([spec.id for spec in envs.registry.all()])

['Acrobot-v1',
 'AirRaid-ram-v0',
 'AirRaid-ram-v4',
 'AirRaid-ramDeterministic-v0',
 'AirRaid-ramDeterministic-v4',
 'AirRaid-ramNoFrameskip-v0',
 'AirRaid-ramNoFrameskip-v4',
 'AirRaid-v0',
 'AirRaid-v4',
 'AirRaidDeterministic-v0',
 'AirRaidDeterministic-v4',
 'AirRaidNoFrameskip-v0',
 'AirRaidNoFrameskip-v4',
 'Alien-ram-v0',
 'Alien-ram-v4',
 'Alien-ramDeterministic-v0',
 'Alien-ramDeterministic-v4',
 'Alien-ramNoFrameskip-v0',
 'Alien-ramNoFrameskip-v4',
 'Alien-v0',
 'Alien-v4',
 'AlienDeterministic-v0',
 'AlienDeterministic-v4',
 'AlienNoFrameskip-v0',
 'AlienNoFrameskip-v4',
 'Amidar-ram-v0',
 'Amidar-ram-v4',
 'Amidar-ramDeterministic-v0',
 'Amidar-ramDeterministic-v4',
 'Amidar-ramNoFrameskip-v0',
 'Amidar-ramNoFrameskip-v4',
 'Amidar-v0',
 'Amidar-v4',
 'AmidarDeterministic-v0',
 'AmidarDeterministic-v4',
 'AmidarNoFrameskip-v0',
 'AmidarNoFrameskip-v4',
 'Ant-v1',
 'Assault-ram-v0',
 'Assault-ram-v4',
 'Assault-ramDeterministic-v0',
 'Assault-ramDeterministic-v4',
 'Assaul

<b>Example: Cart-pole </b>

In [3]:
env = gym.make('CartPole-v0')

In [4]:
for i_ep in range(20):
    obs = env.reset() #initial obs
    for t in range(100):
        env.render()
        print(obs)
        act = env.action_space.sample()
        obs, rew, done, info = env.step(act) #take a random action
        #Step returns obs, rew, done (ep termin), info

[-0.03202714 -0.00578691 -0.0128023   0.02430881]
[-0.03214288 -0.20072295 -0.01231612  0.31292513]
[-0.03615733 -0.00542773 -0.00605762  0.01638366]
[-0.03626589  0.18978057 -0.00572995 -0.27820434]
[-0.03247028 -0.00525917 -0.01129404  0.01266587]
[-0.03257546  0.19002292 -0.01104072 -0.28355895]
[-0.028775    0.38530059 -0.0167119  -0.57970351]
[-0.02106899  0.58065269 -0.02830597 -0.87760382]
[-0.00945594  0.77614765 -0.04585804 -1.17904964]
[ 0.00606702  0.97183409 -0.06943904 -1.48574824]
[ 0.0255037   1.16773027 -0.099154   -1.79928305]
[ 0.0488583   1.36381168 -0.13513966 -2.12106405]
[ 0.07613454  1.17027003 -0.17756094 -1.87300872]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.09953994  0.97747695 -0.21502112 -1.64029495]
[ 0.11908948  1.17437247 -0.24782702 -1.99156724]
[ 0.14257693  0.98255629 -0.28765836 -1.78475119]
[ 0.16222805  0.79157903 -0.32335339 -1.59346598]
[ 0.17805963  0.60139576 -0.3552227  -1.41639327]
[ 0.19008755  0.41194645 -0.38355057 -1.25221352]
[ 0.19832648  0.22316327 -0.40859484 -1.09963305]
[ 0.20278974  0.42076312 -0.4305875  -1.48844534]
[ 0.211205    0.23257779 -0.46035641 -1.3546505 ]
[ 0.21585656  0.42976474 -0.48744942 -1.75025309]
[ 0.22445186  0.62626748 -0.52245448 -2.14837922]
[ 0.23697721  0.43852111 -0.56542206 -2.05103711]
[ 0.24574763  0.25161391 -0.60644281 -1.97182799]
[ 0.25077991  0.44665433 -0.64587937 -2.37978417]
[ 0.25971299  0.64021303 -0.69347505 -2.78859852]
[ 0.27251725  0.83180729 -0.74924702 -3.19753969]
[ 0.2891534   1.0208702  -0.81319781 -3.60542779]
[ 0.3095708   0.83102602 -0.88530637 -3.62333003]
[ 0.32619132  1.0151861  -0.95777297 -4.02579253]
[ 0.34649504  0.8232744  -1.03828882 -4.10063618]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.03379252  0.2449327  -0.01371696 -0.2606398 ]
[ 0.03869118  0.05000922 -0.01892976  0.02768526]
[ 0.03969136 -0.14483622 -0.01837605  0.31433604]
[ 0.03679464  0.05054261 -0.01208933  0.01591502]
[ 0.03780549 -0.1444039  -0.01177103  0.30475923]
[ 0.03491741 -0.33935614 -0.00567584  0.59370674]
[ 0.02813029 -0.53439819  0.00619829  0.8845964 ]
[ 0.01744232 -0.33936094  0.02389022  0.59386844]
[ 0.01065511 -0.14458139  0.03576759  0.30880555]
[ 0.00776348 -0.34019424  0.0419437   0.61255057]
[ 0.00095959 -0.14568279  0.05419471  0.33336784]
[-0.00195406 -0.34153253  0.06086207  0.64263659]
[-0.00878471 -0.53744764  0.0737148   0.95384754]
[-0.01953367 -0.73347977  0.09279175  1.26874972]
[-0.03420326 -0.9296561   0.11816674  1.58898992]
[-0.05279638 -1.12596696  0.14994654  1.91606295]
[-0.07531572 -0.93274382  0.1882678   1.67339973]
[-0.0939706  -1.12948689  0.2217358   2.01832396]
[-0.11656034 -0.93724804  0.26210227  1.80168294]
[-0.1353053  -1.13417114  0.29813593  2.16315824]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.39574334  0.40338198  6.3025242   4.22258215]
[-0.3876757   0.20832447  6.38697585  4.52079898]
[-0.38350921  0.40388077  6.47739183  4.25950274]
[-0.37543159  0.20998757  6.56258188  4.60161356]
[-0.37123184  0.40591465  6.65461415  4.40019748]
[-0.36311355  0.21464198  6.7426181   4.77424855]
[-0.35882071  0.41109816  6.83810307  4.6404931 ]
[-0.35059874  0.60688998  6.93091293  4.54577583]
[-0.33846094  0.42195786  7.02182845  4.94438144]
[-0.33002179  0.24173273  7.12071608  5.34221036]
[-0.32518713  0.06721551  7.22756029  5.73585665]
[-0.32384282  0.27170905  7.34227742  5.79420876]
[-0.31840864  0.10812245  7.4581616   6.17070435]
[-0.31624619 -0.04809378  7.58157568  6.53231973]
[-0.31720807  0.16869306  7.71222208  6.72798931]
[-0.31383421  0.38968084  7.84678186  6.97220671]
[-0.30604059  0.61559489  7.986226    7.26375932]
[-0.29372869  0.84698092  8.13150118  7.60095782]
[-0.27678907  0.71853929  8.28352034  7.83092487]
[-0.26241829  0.9589442   8.44013884  8.24839277]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.44763233  0.86698072 -1.77840036 -5.99104591]
[ 0.46497195  0.64990943 -1.89822128 -6.3458458 ]
[ 0.47797013  0.79401035 -2.02513819 -6.5547111 ]
[ 0.49385034  0.5688697  -2.15623242 -6.96709639]
[ 0.50522774  0.33933954 -2.29557434 -7.4023817 ]
[ 0.51201453  0.48149197 -2.44362198 -7.48111976]
[ 0.52164437  0.25117807 -2.59324437 -7.93474483]
[ 0.52666793  0.40484556 -2.75193927 -7.89129398]
[ 0.53476484  0.1839382  -2.90976515 -8.30949759]
[ 0.5384436  -0.02904523 -3.0759551  -8.6879746 ]
[ 0.5378627   0.16024843 -3.24971459 -8.42392914]
[ 0.54106767 -0.02570561 -3.41819318 -8.66950543]
[ 0.54055355 -0.19610544 -3.59158328 -8.83510208]
[ 0.53663144 -0.350351   -3.76828533 -8.91556059]
[ 0.52962442 -0.48967429 -3.94659654 -8.91241054]
[ 0.51983094 -0.61693266 -4.12484475 -8.83279131]
[ 0.50749229 -0.73604916 -4.30150057 -8.68713656]
[ 0.4927713  -0.85133242 -4.47524331 -8.4866776 ]
[ 0.47574465 -0.96689024 -4.64497686 -8.24162777]
[ 0.45640685 -1.08623798 -4.80980941 -7.96035464]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.09479221  0.61707446 -0.29762104 -1.55364502]
[ 0.1071337   0.42648188 -0.32869394 -1.36653925]
[ 0.11566334  0.23660128 -0.35602472 -1.19187161]
[ 0.12039536  0.43416918 -0.37986215 -1.57211318]
[ 0.12907875  0.63135203 -0.41130442 -1.95581639]
[ 0.14170579  0.44220587 -0.45042074 -1.81330206]
[ 0.15054991  0.63882542 -0.48668679 -2.20680756]
[ 0.16332641  0.45042545 -0.53082294 -2.09452484]
[ 0.17233492  0.26291423 -0.57271343 -2.00079842]
[ 0.17759321  0.07621925 -0.6127294  -1.92476418]
[ 0.17911759  0.27128913 -0.65122469 -2.33321886]
[ 0.18454338  0.46490049 -0.69788906 -2.74241105]
[ 0.19384139  0.27777858 -0.75273728 -2.71627664]
[ 0.19939696  0.46860912 -0.80706282 -3.12617452]
[ 0.20876914  0.28092851 -0.86958631 -3.14381233]
[ 0.21438771  0.46777107 -0.93246255 -3.54925677]
[ 0.22374313  0.27857064 -1.00344769 -3.61626022]
[ 0.22931454  0.08905124 -1.07577289 -3.71142786]
[ 0.23109557  0.26819297 -1.15000145 -4.09778792]
[ 0.23645943  0.07522846 -1.23195721 -4.2479057 ]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[  1.36395433   0.13063547 -12.08756683  -8.02725618]
[  1.36656704  -0.03875683 -12.24811196  -7.66628979]
[  1.3657919   -0.21890837 -12.40143775  -7.31763635]
[  1.36141373  -0.01792819 -12.54779048  -7.56674477]
[  1.36105517  -0.21227383 -12.69912537  -7.26981438]
[-0.03913382  0.00211435  0.01209778 -0.02524843]
[-0.03909153  0.19706074  0.01159281 -0.31408995]
[-0.03515032  0.00177558  0.00531101 -0.01777369]
[-0.0351148   0.19682096  0.00495554 -0.30877621]
[-0.03117838  0.00162876 -0.00121999 -0.01453457]
[-0.03114581 -0.19347568 -0.00151068  0.27776319]
[-0.03501532  0.00166779  0.00404459 -0.01539582]
[-0.03498197  0.19673151  0.00373667 -0.3067999 ]
[-0.03104734  0.00155651 -0.00239933 -0.01294087]
[-0.03101621 -0.19353095 -0.00265815  0.27898408]
[-0.03488683  0.00162882  0.00292154 -0.01453604]
[-0.03485425  0.19670875  0.00263081 -0.30629575]
[-0.03092007  0.39179311 -0.0034951  -0.59814783]
[-0.02308421  0.19672024 -0.01545806 -0.30656786]
[-0.01914981  0.00182194 -0.02

You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.93671104 -2.39947064 -0.22899759  0.4087125 ]
[-0.98470046 -2.20195984 -0.22082334  0.05344209]
[-1.02873965 -2.39334559 -0.2197545   0.26915399]
[-1.07660657 -2.19587455 -0.21437142 -0.08401816]
[-1.12052406 -2.38738274 -0.21605178  0.13412519]
[-1.16827171 -2.5788616  -0.21336928  0.35163986]
[-1.21984894 -2.77041263 -0.20633648  0.57019504]
[-1.2752572  -2.57308581 -0.19493258  0.22024996]
[-1.32671891 -2.76496482 -0.19052758  0.44566949]
[-1.38201821 -2.95695286 -0.18161419  0.67276354]
[-1.44115727 -3.14914808 -0.16815892  0.9032134 ]
[-1.50414023 -2.95219658 -0.15009465  0.56274723]
[-1.56318416 -2.75532254 -0.1388397   0.22679404]
[-1.61829061 -2.55851766 -0.13430382 -0.10626042]
[-1.66946096 -2.7514849  -0.13642903  0.14121714]
[-1.72449066 -2.94441597 -0.13360469  0.38793884]
[-1.78337898 -2.74767565 -0.12584591  0.05629531]
[-1.83833249 -2.94078956 -0.12472001  0.30677431]
[-1.89714828 -2.74413153 -0.11858452 -0.02249414]
[-1.95203092 -2.54752621 -0.1190344  -0.3501132 ]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.33491048 -0.75502423  1.23678496  4.7095783 ]
[-0.35001096 -0.55684335  1.33097653  4.88987431]
[-0.36114783 -0.35622176  1.42877402  5.10398052]
[-0.36827226 -0.51668772  1.53085363  5.42909027]
[-0.37860602 -0.67228193  1.63943543  5.73217558]
[-0.39205166 -0.82343377  1.75407894  6.00993311]
[-0.40852033 -0.97090537  1.87427761  6.25869196]
[-0.42793844 -0.74994771  1.99945144  6.6383046 ]
[-0.44293739 -0.52397926  2.13221754  7.04659011]
[-0.45341698 -0.29347258  2.27314934  7.47954002]
[-0.45928643 -0.05958847  2.42274014  7.9305965 ]
[-0.4604782  -0.20265637  2.58135207  7.96270067]
[-0.46453133 -0.35529782  2.74060608  7.92496923]
[-0.47163728 -0.13357716  2.89910547  8.34592477]
[-0.47430883 -0.30830176  3.06602396  8.16210019]
[-0.48047486 -0.4973583   3.22926597  7.90152076]
[-0.49042203 -0.30892644  3.38729638  8.15734   ]
[-0.49660056 -0.52229919  3.55044318  7.77538116]
[-0.50704654 -0.74354271  3.70595081  7.35398761]
[-0.52191739 -0.96865471  3.85303056  6.91142824]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.00245038  0.3506889  -0.03311416 -0.60034926]
[ 0.00946416  0.15604547 -0.04512114 -0.31827797]
[ 0.01258507 -0.03840576 -0.0514867  -0.0401591 ]
[ 0.01181696 -0.23275304 -0.05228988  0.23584511]
[ 0.0071619  -0.03692452 -0.04757298 -0.07286241]
[ 0.00642341  0.15884603 -0.04903023 -0.38016717]
[ 0.00960033  0.3546287  -0.05663357 -0.68789737]
[ 0.0166929   0.55048907 -0.07039152 -0.99785828]
[ 0.02770268  0.74647794 -0.09034869 -1.31179158]
[ 0.04263224  0.55260869 -0.11658452 -1.04870018]
[ 0.05368441  0.74906822 -0.13755852 -1.37558729]
[ 0.06866578  0.55590688 -0.16507027 -1.12889705]
[ 0.07978392  0.36328577 -0.18764821 -0.89220345]
[ 0.08704963  0.56038937 -0.20549228 -1.23751419]
[ 0.09825742  0.36841221 -0.23024256 -1.0155975 ]
[ 0.10562566  0.56573908 -0.25055451 -1.37087176]
[ 0.11694044  0.37446772 -0.27797195 -1.16581808]
[ 0.1244298   0.18381665 -0.30128831 -0.97149437]
[ 0.12810613 -0.00628946 -0.3207182  -0.78642491]
[ 0.12798034  0.19149461 -0.33644669 -1.16065626]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 2.60237974  2.63685089 -6.08451598 -1.45078339]
[ 2.65511675  2.82905547 -6.11353165 -1.67539397]
[ 2.71169786  2.63241938 -6.14703953 -1.33503516]
[ 2.76434625  2.82558848 -6.17374023 -1.58220424]
[ 2.82085802  2.6293475  -6.20538432 -1.25749133]
[ 2.87344497  2.43332082 -6.23053415 -0.94149034]
[ 2.92211139  2.62769519 -6.24936395 -1.21717558]
[ 2.97466529  2.4321538  -6.27370746 -0.91408965]
[ 3.02330837  2.23690494 -6.29198926 -0.61844307]
[ 3.06804646  2.43214875 -6.30435812 -0.91388577]
[ 3.11668944  2.2373195  -6.32263583 -0.62793173]
[ 3.16143583  2.4329692  -6.33519447 -0.93277338]
[ 3.21009521  2.2385861  -6.35384994 -0.6568768 ]
[ 3.25486694  2.04451528 -6.36698747 -0.3872552 ]
[ 3.29575724  2.24072063 -6.37473258 -0.7051394 ]
[ 3.34057165  2.0469784  -6.38883536 -0.44262033]
[-0.02222937  0.04109606  0.02062945 -0.00080848]
[-0.02140745  0.23591617  0.02061328 -0.28691184]
[-0.01668913  0.43073818  0.01487504 -0.5730229 ]
[-0.00807436  0.23541086  0.00341459 -0.27569123]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.63359173  0.57531288 -1.42304718 -4.98663775]
[ 0.64509798  0.37278163 -1.52277993 -5.232712  ]
[ 0.65255362  0.16670839 -1.62743417 -5.51153651]
[ 0.65588778  0.32023364 -1.7376649  -5.79202905]
[ 0.66229246  0.47007066 -1.85350548 -6.04461448]
[ 0.67169387  0.6171923  -1.97439777 -6.26538243]
[ 0.68403772  0.39539591 -2.09970542 -6.6664204 ]
[ 0.69194564  0.16894418 -2.23303383 -7.0916462 ]
[ 0.69532452 -0.06134584 -2.37486675 -7.53590212]
[ 0.6940976   0.08308488 -2.52558479 -7.58384825]
[ 0.6957593  -0.14563383 -2.67726176 -8.0337334 ]
[ 0.69284662  0.01321662 -2.83793643 -7.95234646]
[ 0.69311096  0.18467661 -2.99698336 -7.7948323 ]
[ 0.69680449  0.36893124 -3.15288    -7.56370226]
[ 0.70418311  0.56484321 -3.30415405 -7.26653462]
[ 0.71547998  0.77019953 -3.44948474 -6.91497843]
[ 0.73088397  0.59453734 -3.58778431 -7.07698396]
[ 0.74277471  0.42834842 -3.72932399 -7.17499102]
[ 0.75134168  0.27122708 -3.87282381 -7.20811027]
[ 0.75676622  0.12195438 -4.01698601 -7.17844835]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.28057299 -0.22998143  0.78823796  2.71962129]
[-0.28517261 -0.04376468  0.84263038  2.73114921]
[-0.28604791  0.14208904  0.89725337  2.76506072]
[-0.28320613 -0.04579602  0.95255458  3.17064853]
[-0.28412205  0.14144651  1.01596755  3.24743921]
[-0.28129312 -0.04167143  1.08091634  3.64203566]
[-0.28212655 -0.22110612  1.15375705  4.02809953]
[-0.28654867 -0.39634743  1.23431904  4.40337506]
[-0.29447562 -0.56695989  1.32238654  4.76538373]
[-0.30581481 -0.36749363  1.41769422  4.97679726]
[-0.31316469 -0.52932917  1.51723016  5.30437929]
[-0.32375127 -0.68635062  1.62331775  5.61056812]
[-0.33747828 -0.83891955  1.73552911  5.89214854]
[-0.35425667 -0.62341038  1.85337208  6.23518004]
[-0.36672488 -0.76847768  1.97807568  6.45684642]
[-0.38209443 -0.91217204  2.10721261  6.64141904]
[-0.40033788 -1.05621844  2.24004099  6.78370117]
[-0.42146224 -1.20256389  2.37571502  6.87809488]
[-0.44551352 -1.35323072  2.51327691  6.91899164]
[-0.47257814 -1.51011464  2.65165675  6.90141682]



- Action space: Discrete: validactions are 0 or 1
- Observation space: Box: observations will be array of 4 numbers

In [4]:
#Discrete
print("action space - ",env.action_space)
print("observation space - ", env.observation_space)
#Box
print("observation space upper bound- ", env.observation_space.high)
print("observation space lower bound- ", env.observation_space.low)

action space -  Discrete(2)
observation space -  Box(4,)
observation space upper bound-  [  4.80000000e+00   3.40282347e+38   4.18879020e-01   3.40282347e+38]
observation space lower bound-  [ -4.80000000e+00  -3.40282347e+38  -4.18879020e-01  -3.40282347e+38]


In [ ]:
space = gym.spaces.Discrete(8)
x=space.sample()
assert space.contains(x)
assert space.n==8

<h2>Simple Bellman optimisation</h2>

In [48]:
n_eps= 10

In [13]:
env = gym.make('FrozenLake-v0')
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [21]:
Q = np.zeros((env.observation_space.n, env.action_space.n))
alpha = 0.1 #Learning rate

In [26]:
class RandomAgent(object):
    """The world's simplest agent!"""
    def __init__(self, action_space):
        self.action_space = action_space

    def act(self, observation, reward, done):
        return self.action_space.sample()

In [53]:
#Initialise
rew0 = 0
done0 = False

agent = RandomAgent(env.action_space)

for i in range(n_eps):
    obs0 = env.reset()
    while not done0:
        a0 = agent.act(obs0, rew0, done0)
        obs0, rew0, done0, info0 = env.step(a0)

In [50]:
print('Reward %d \ndone %s'%(rew0, done0))

Reward 0 
done True


In [44]:
info0

{'prob': 0.3333333333333333}

In [55]:
ac = np.argmax(Q) #Choose action greedily
Q = Q + alpha*(lamb*np.max(Q[s1,:]) - Q[s,a]) #Update reward table

0