In [25]:
import gym
import numpy as np

In [2]:
env = gym.make('CartPole-v0')

In [3]:
for i_ep in range(20):
    obs = env.reset() #initial obs
    for t in range(100):
        env.render()
        print(obs)
        act = env.action_space.sample()
        obs, rew, done, info = env.step(act) #take a random action
        #Step returns obs, rew, done (ep termin), info

[-0.02376196  0.04594762  0.0013865   0.00208167]
[-0.022843   -0.14919419  0.00142813  0.29520173]
[-0.02582689  0.04590738  0.00733216  0.00296956]
[-0.02490874  0.24092341  0.00739156 -0.28739099]
[-0.02009027  0.04569683  0.00164374  0.00761397]
[-0.01917633  0.24079517  0.00179601 -0.28454988]
[-0.01436043  0.43589146 -0.00389498 -0.57666582]
[-0.0056426   0.63106779 -0.0154283  -0.87057322]
[ 0.00697875  0.82639616 -0.03283976 -1.16806664]
[ 0.02350668  1.02192962 -0.0562011  -1.47086184]
[ 0.04394527  1.21769212 -0.08561833 -1.7805564 ]
[ 0.06829911  1.41366661 -0.12122946 -2.0985824 ]
[ 0.09657244  1.21995398 -0.16320111 -1.84570024]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.12097152  1.02696402 -0.20011511 -1.60783032]
[ 0.1415108   1.22380942 -0.23227172 -1.95564793]
[ 0.16598699  1.03178566 -0.27138468 -1.74302271]
[ 0.18662271  0.84057827 -0.30624513 -1.54552005]
[ 0.20343427  0.65014276 -0.33715553 -1.36179286]
[ 0.21643713  0.46041857 -0.36439139 -1.19048535]
[ 0.2256455   0.27133647 -0.3882011  -1.03026059]
[ 0.23107223  0.46901861 -0.40880631 -1.416006  ]
[ 0.2404526   0.28052957 -0.43712643 -1.27344002]
[ 0.24606319  0.47789407 -0.46259523 -1.66611139]
[ 0.25562107  0.67466744 -0.49591746 -2.06145332]
[ 0.26911442  0.48668915 -0.53714653 -1.95335039]
[ 0.2788482   0.29955245 -0.57621353 -1.86261222]
[ 0.28483925  0.49513412 -0.61346578 -2.2688011 ]
[ 0.29474194  0.68940455 -0.6588418  -2.67632835]
[ 0.30853003  0.88191143 -0.71236837 -3.08463888]
[ 0.32616825  1.0721143  -0.77406114 -3.49272838]
[ 0.34761054  0.88261712 -0.84391571 -3.49498981]
[ 0.36526288  1.06836651 -0.91381551 -3.89983899]
[ 0.38663021  0.87720135 -0.99181229 -3.95751473]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 1.78597968  1.49917817 -5.30469568  0.0467706 ]
[ 1.81596324  1.67862151 -5.30376027  0.14042076]
[ 1.84953567  1.48656324 -5.30095185  0.54510151]
[ 1.87926694  1.66621054 -5.29004982  0.6400317 ]
[ 1.91259115  1.47469732 -5.27724919  1.04319617]
[ 1.9420851   1.28394574 -5.25638527  1.44469056]
[ 1.96776401  1.46477191 -5.22749145  1.55586837]
[ 1.99705945  1.27601662 -5.19637409  1.95119768]
[ 2.02257978  1.458082   -5.15735013  2.08435575]
[ 2.05174142  1.64057849 -5.11566302  2.23190223]
[ 2.08455299  1.8236607  -5.07102497  2.39454693]
[ 2.12102621  2.00751201 -5.02313403  2.57304463]
[ 2.16117645  2.19234841 -4.97167314  2.76818819]
[ 2.20502341  2.37842219 -4.91630938  2.98080005]
[ 2.25259186  2.20136881 -4.85669338  3.32249106]
[ 2.29661923  2.39148438 -4.79024356  3.57242618]
[ 2.34444892  2.58391258 -4.71879503  3.84308618]
[ 2.39612717  2.4154347  -4.64193331  4.13869906]
[ 2.44443587  2.25003209 -4.55915933  4.41450378]
[ 2.48943651  2.45169503 -4.47086925  4.75122901]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.56381744  0.36873536  4.24427749  8.03535114]
[-0.55644273  0.12578115  4.40498451  7.60854704]
[-0.55392711 -0.11153278  4.55715545  7.22061738]
[-0.55615776  0.0216335   4.7015678   6.96103602]
[-0.55572509  0.15925983  4.84078852  6.66928711]
[-0.5525399  -0.06121068  4.97417426  6.42005318]
[-0.55376411  0.08843822  5.10257533  6.07797499]
[-0.55199534  0.24544687  5.22413483  5.71649267]
[-0.54708641  0.40975565  5.33846468  5.33946369]
[-0.53889129  0.58092423  5.44525395  4.95077641]
[-0.52727281  0.75823688  5.54426948  4.55432402]
[-0.51210807  0.56310238  5.63535596  4.57268377]
[-0.50084602  0.3677759   5.72680964  4.62889612]
[-0.49349051  0.17204029  5.81938756  4.7229518 ]
[-0.4900497   0.3604066   5.9138466   4.33873057]
[-0.48284157  0.16534293  6.00062121  4.50546162]
[-0.47953471  0.35768911  6.09073044  4.14641119]
[-0.47238093  0.16257366  6.17365866  4.37744785]
[-0.46912945  0.35704036  6.26120762  4.05535918]
[-0.46198865  0.55211791  6.3423148   3.7563526 ]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.45020502  0.48583213 -1.15414031 -4.18848073]
[ 0.45992166  0.65995635 -1.23790992 -4.56303162]
[ 0.47312079  0.46294164 -1.32917056 -4.7443235 ]
[ 0.48237962  0.62864353 -1.42405703 -5.08925696]
[ 0.49495249  0.78933598 -1.52584216 -5.41534042]
[ 0.51073921  0.94514257 -1.63414897 -5.71954609]
[ 0.52964207  0.73274237 -1.74853989 -6.03312697]
[ 0.54429691  0.87998046 -1.86920243 -6.28344548]
[ 0.56189652  0.65879733 -1.99487134 -6.66199334]
[ 0.57507247  0.43258251 -2.12811121 -7.06957435]
[ 0.58372412  0.57251104 -2.2695027  -7.20807153]
[ 0.59517434  0.34142731 -2.41366413 -7.65613916]
[ 0.60200289  0.4866736  -2.56678691 -7.68909324]
[ 0.61173636  0.25858164 -2.72056878 -8.1360884 ]
[ 0.61690799  0.0344554  -2.88329054 -8.56307504]
[ 0.6175971   0.20693844 -3.05455205 -8.38803281]
[  6.21735868e-01   4.71912370e-03  -3.22231270e+00  -8.71577114e+00]
[ 0.62183025 -0.183185   -3.39662812 -8.97300363]
[ 0.61816655 -0.35419271 -3.5760882  -9.14704793]
[ 0.6110827  -0.50748944 -3.75

You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.13096787  0.42573958 -0.30963528 -1.29388882]
[ 0.13948266  0.23557408 -0.33551306 -1.11179074]
[ 0.14419414  0.43319012 -0.35774887 -1.48848721]
[ 0.15285794  0.63048896 -0.38751862 -1.86864719]
[ 0.16546772  0.44107648 -0.42489156 -1.7166963 ]
[ 0.17428925  0.63795155 -0.45922549 -2.10694398]
[ 0.18704828  0.44932    -0.50136437 -1.98362778]
[ 0.19603468  0.26157093 -0.54103692 -1.87796725]
[ 0.2012661   0.07463633 -0.57859627 -1.7890311 ]
[ 0.20275883  0.27033466 -0.61437689 -2.19557187]
[ 0.20816552  0.46477331 -0.65828833 -2.60337131]
[ 0.21746099  0.27767022 -0.71035575 -2.56122066]
[ 0.22301439  0.46973289 -0.76158016 -2.97135178]
[ 0.23240905  0.28235833 -0.8210072  -2.97081365]
[ 0.23805622  0.4709411  -0.88042347 -3.37874676]
[ 0.24747504  0.28247146 -0.94799841 -3.42539012]
[ 0.25312447  0.09394736 -1.01650621 -3.4992395 ]
[ 0.25500341  0.2757147  -1.086491   -3.89272723]
[ 0.26051771  0.08438356 -1.16434555 -4.01929296]
[ 0.26220538 -0.10812289 -1.2447314  -4.17517907]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[  1.40561174  -0.01860586 -12.46613989  -7.4307797 ]
[  1.40523963  -0.20962535 -12.61475548  -7.11627001]
[  1.40104712  -0.01623325 -12.75708088  -7.42023827]
[  1.40072245  -0.21833701 -12.90548565  -7.17830844]
[-0.02586413 -0.010169    0.01364291  0.02268274]
[-0.02606751  0.18475467  0.01409656 -0.26566466]
[-0.02237241 -0.01056561  0.00878327  0.0314309 ]
[-0.02258373  0.18442929  0.00941189 -0.25846792]
[-0.01889514 -0.01082575  0.00424253  0.03716873]
[-0.01911166 -0.20600828  0.0049859   0.33118719]
[-0.02323182 -0.01095766  0.01160965  0.04008074]
[-0.02345097  0.18399591  0.01241126 -0.24891674]
[-0.01977106 -0.01130107  0.00743293  0.04765498]
[-0.01999708 -0.20652881  0.00838603  0.34267376]
[-0.02412765 -0.01152717  0.0152395   0.05264704]
[-0.0243582   0.18337299  0.01629244 -0.23518901]
[-0.02069074  0.37825842  0.01158866 -0.52268859]
[-0.01312557  0.18297529  0.00113489 -0.22637658]
[-0.00946606 -0.01216286 -0.00339264  0.06666412]
[-0.00970932 -0.207236   -0.002059

You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.83370229 -2.46501945 -1.20713088 -3.24330011]
[-0.88300268 -2.28615297 -1.27199688 -3.61350714]
[-0.92872574 -2.11088408 -1.34426703 -3.97187183]
[-0.97094342 -2.30441835 -1.42370446 -4.19315987]
[-1.01703178 -2.13622795 -1.50756766 -4.52096059]
[-1.05975634 -2.3358016  -1.59798687 -4.79545755]
[-1.10647238 -2.53889131 -1.69389602 -5.09763103]
[-1.1572502  -2.74599561 -1.79584864 -5.42755148]
[-1.21217011 -2.59266877 -1.90439967 -5.66281349]
[-1.26402349 -2.80773896 -2.01765594 -6.0462419 ]
[-1.32017827 -3.02753392 -2.13858078 -6.45384549]
[-1.38072895 -3.25175638 -2.26765769 -6.88258391]
[-1.44576407 -3.1054296  -2.40530937 -6.96716901]
[-1.50787267 -2.95423522 -2.54465275 -6.9965557 ]
[-1.56695737 -2.79627797 -2.68458386 -6.96585719]
[-1.62288293 -3.0148541  -2.82390101 -7.38980695]
[-1.68318001 -3.22934284 -2.97169715 -7.78727834]
[-1.74776687 -3.04699544 -3.12744271 -7.5674046 ]
[-1.80870678 -3.24310794 -3.2787908  -7.86570384]
[-1.87356894 -3.03806823 -3.43610488 -7.52082457]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.39117235 -0.83974948  2.48186981  7.06144498]
[-0.40796734 -0.61406907  2.62309871  7.50912314]
[-0.42024872 -0.38954645  2.77328117  7.94734071]
[-0.42803965 -0.16950874  2.93222799  8.36111453]
[-0.43142982  0.04203543  3.09945028  8.73260612]
[-0.43058912 -0.1493236   3.2741024   8.45820861]
[-0.43357559 -0.35528235  3.44326657  8.11313485]
[-0.44068123 -0.18441306  3.60552927  8.27051125]
[-0.4443695  -0.41180374  3.7709395   7.83392196]
[-0.45260557 -0.64312814  3.92761793  7.38036041]
[-0.46546813 -0.4980899   4.07522514  7.32608047]
[-0.47542993 -0.73114078  4.22174675  6.881798  ]
[-0.49005275 -0.95995141  4.35938271  6.46076029]
[-0.50925178 -1.18353368  4.48859792  6.06894365]
[-0.53292245 -1.03676316  4.60997679  5.83113377]
[-0.55365771 -1.25084201  4.72659947  5.50584523]
[-0.57867455 -1.09638752  4.83671637  5.20858271]
[-0.6006023  -0.93723073  4.94088803  4.88724709]
[-0.61934692 -1.13795213  5.03863297  4.66908875]
[-0.64210596 -0.96967166  5.13201474  4.30969878]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.54459595  0.26653418  8.72739708  8.10485053]
[-0.53926527  0.12393271  8.88949409  8.12969915]
[-0.53678661  0.35385972  9.05208807  8.57631277]
[-0.52970942  0.57780178  9.22361433  8.99621771]
[ 0.01163736  0.0121708   0.03378891 -0.0423717 ]
[ 0.01188077 -0.18341897  0.03294147  0.26077755]
[ 0.00821239  0.01121763  0.03815702 -0.02133592]
[ 0.00843675  0.20577218  0.0377303  -0.30173989]
[ 0.01255219  0.01013336  0.03169551  0.00259957]
[ 0.01275486  0.20478675  0.0317475  -0.27991695]
[ 0.01685059  0.00922664  0.02614916  0.02260759]
[ 0.01703512  0.20396402  0.02660131 -0.26171163]
[ 0.0211144   0.39869634  0.02136708 -0.54588692]
[ 0.02908833  0.20328079  0.01044934 -0.24654905]
[ 0.03315395  0.00801117  0.00551836  0.04941144]
[ 0.03331417  0.20305356  0.00650659 -0.2415253 ]
[ 0.03737524  0.39808197  0.00167608 -0.5321488 ]
[ 0.04533688  0.20293648 -0.00896689 -0.23893821]
[ 0.04939561  0.39818538 -0.01374566 -0.53443601]
[ 0.05735932  0.2032594  -0.02443438 -0.24611576]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 2.18890924  1.88202758 -5.83489625 -1.29217661]
[ 2.22654979  1.68472202 -5.86073978 -0.89803517]
[ 2.26024423  1.87249406 -5.87870048 -1.03439469]
[ 2.29769411  1.67483433 -5.89938838 -0.64612795]
[ 2.3311908   1.47691597 -5.91231094 -0.26076187]
[ 2.36072912  1.66540592 -5.91752617 -0.41771931]
[ 2.39403724  1.85403511 -5.92588056 -0.57683312]
[ 2.43111794  2.04288117 -5.93741722 -0.7393851 ]
[ 2.47197556  2.23202126 -5.95220493 -0.90666167]
[ 2.51661599  2.42153184 -5.97033816 -1.0799575 ]
[ 2.56504662  2.61148782 -5.99193731 -1.26057707]
[ 2.61727638  2.80196108 -6.01714885 -1.44983317]
[ 2.6733156   2.60473792 -6.04614551 -1.08711037]
[ 2.72541036  2.79608498 -6.06788772 -1.2970662 ]
[ 2.78133206  2.59897879 -6.09382904 -0.94542322]
[ 2.83331164  2.40188073 -6.11273751 -0.59972201]
[ 2.88134925  2.59425979 -6.12473195 -0.83423956]
[ 2.93323445  2.39736907 -6.14141674 -0.4962127 ]
[ 2.98118183  2.20056252 -6.15134099 -0.16242404]
[ 3.02519308  2.39357477 -6.15458948 -0.4107797 ]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[ 0.3703725   0.81323925 -0.5792557  -2.43682326]
[ 0.38663729  1.00750056 -0.62799217 -2.8416165 ]
[ 0.4067873   0.81932141 -0.6848245  -2.78593339]
[ 0.42317373  1.01106637 -0.74054316 -3.19466766]
[ 0.44339506  0.82264436 -0.80443652 -3.18441415]
[ 0.45984794  0.63469834 -0.8681248  -3.20070777]
[ 0.47254191  0.82131411 -0.93213896 -3.60596768]
[ 0.48896819  0.63180959 -1.00425831 -3.67256878]
[ 0.50160438  0.81289027 -1.07770968 -4.06641828]
[ 0.51786219  0.62046277 -1.15903805 -4.18876833]
[ 0.53027144  0.79446511 -1.24281342 -4.56265454]
[ 0.54616075  0.59741168 -1.33406651 -4.74576613]
[ 0.55810898  0.39798856 -1.42898183 -4.96141197]
[ 0.56606875  0.55974373 -1.52821007 -5.28675418]
[ 0.57726363  0.71676389 -1.63394515 -5.59051494]
[ 0.5915989   0.50569078 -1.74575545 -5.90390918]
[ 0.60171272  0.65432169 -1.86383364 -6.15461307]
[ 0.61479915  0.43459001 -1.9869259  -6.53128812]
[ 0.62349095  0.20985696 -2.11755166 -6.93646177]
[ 0.62768809 -0.01948706 -2.25628089 -7.3664615 ]


You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


[-0.06034086 -0.22556793  0.03280266  0.33618874]
[-0.06485222 -0.42114097  0.03952643  0.63903274]
[-0.07327504 -0.6167911   0.05230709  0.94389646]
[-0.08561086 -0.81257724  0.07118502  1.25254527]
[-0.1018624  -0.61843574  0.09623592  0.98298126]
[-0.11423112 -0.81470617  0.11589555  1.30427438]
[-0.13052524 -1.01109133  0.14198103  1.63087304]
[-0.15074707 -0.81789421  0.17459849  1.38559572]
[-0.16710495 -0.6253255   0.20231041  1.15220582]
[-0.17961146 -0.82242783  0.22535452  1.50090379]
[-0.19606002 -0.63063907  0.2553726   1.28618961]
[-0.2086728  -0.8279374   0.28109639  1.64680544]
[-0.22523155 -0.63697905  0.3140325   1.45316836]
[-0.23797113 -0.44676214  0.34309587  1.27261218]
[-0.24690637 -0.6442605   0.36854811  1.65049656]
[-0.25979158 -0.45480007  0.40155804  1.49130578]
[-0.26888758 -0.65202886  0.43138416  1.87852632]
[-0.28192816 -0.8486433   0.46895469  2.26935937]
[-0.29890103 -0.65985413  0.51434187  2.1496223 ]
[-0.31209811 -0.47198397  0.55733432  2.04891477]



- Action space: Discrete: validactions are 0 or 1
- Observation space: Box: observations will be array of 4 numbers

In [8]:
#Discrete
print("action space - ",env.action_space)
print("observation space - ", env.observation_space)
#Box
print("observation space upper bound- ", env.observation_space.high)
print("observation space lower bound- ", env.observation_space.low)

action space -  Discrete(2)
observation space -  Box(4,)
observation space upper bound-  [  4.80000000e+00   3.40282347e+38   4.18879020e-01   3.40282347e+38]
observation space lower bound-  [ -4.80000000e+00  -3.40282347e+38  -4.18879020e-01  -3.40282347e+38]


In [8]:
space = gym.spaces.Discrete(8)
x=space.sample()
assert space.contains(x)
assert space.n==8

<h2>Gridworld</h2>

We can explore the same random step process through gridworld (or in the case of OpenGym 'Frozen Lake'). Where the goal is to get from S (start) to G (goal) stepping only on safe F (frozen) squares and avoiding H (holes)

In [22]:
env=gym.make('FrozenLake-v0')

In [23]:
P = env.env.P #transition probs P[s][a]
P[0][0] #Prob, next state, reward, done

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 4, 0.0, False)]

In [14]:
for i_ep in range(10):
    obs = env.reset() #initial obs
    for t in range(10):
        env.render()
        print(obs)
        act = env.action_space.sample()
        obs, rew, done, info = env.step(act) #take a random action
        #Step returns obs, rew, done (ep termin), info


SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0

SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Left)
SFFF
FHFH
FFFH
HFFG
8
  (Up)
SFFF
FHFH
FFFH
HFFG
8
  (Right)
SFFF
FHFH
FFFH
HFFG
4
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Up)
SFFF
FHFH
FFFH
HFFG
0
  (Down)
SFFF
FHFH
FFFH
HFFG
1

SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
1
  (Right)
SFFF
FHFH
FFFH
HFFG
1
  (Left)
SFFF
FHFH
FFFH
HFFG
1
  (Down)
SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
4
  (Up)
SFFF
FHFH
FFFH
HFFG
5
  (Left)
SFFF
FHFH
FFFH
HFFG
5
  (Right)
SFFF
FHFH
FFFH
HFFG
5
  (Right)
SFFF
FHFH
FFFH
HFFG
5

SFFF
FHFH
FFFH
HFFG
0
  (Left)
SFFF
FHFH
FFFH
HFFG
0
  (Right)
SFFF
FHFH
FFFH
HFFG
4
  (Right)
SFFF


The process above is random. To add some control, we can introduce dynamic programming (DP). DP uses a full backup and therefore requires full knowledge of our environment

In [56]:
def policy_eval(policy, env, lambd=0.01):
    V = np.zeros(env.env.nS) #grid_h * grid_w values
    # pol(s|a)* (rew* disc(sum(prob of ss * val ss))) 
    for s in range(env.env.nS): #for each state do full backup
        v=0
        for a, action_p in enumerate(policy[s]): #from that state, for all possible actions
            for prob, next_state, rew, done in env.env.P[s][a]: #for all next states
                v+= action_p * prob * (rew + lambd*V[s]) #update reward
        V[s] = v
    return v

In [57]:
#Initialise value to zero

#Take steps
rand_pol = np.ones([env.env.nS, env.env.nA])/env.env.nA
policy_eval(rand_pol, env, V)
#When done=True
#return value

ValueError: setting an array element with a sequence.